"""Default configuration values"""

# GROMACS defaults
DEFAULT_FORCEFIELD = "amber99sb-ildn"
DEFAULT_WATER_MODEL = "tip3p"
DEFAULT_BOX_TYPE = "cubic"
DEFAULT_BOX_DISTANCE = 1.0

# Temperature and pressure
DEFAULT_TEMPERATURE = 300  # K
DEFAULT_PRESSURE = 1.0  # bar

# Simulation parameters
DEFAULT_MINIMIZATION_STEPS = 5000
DEFAULT_EQUILIBRATION_TIME = 100  # ps
DEFAULT_PRODUCTION_TIME = 1000  # ps
DEFAULT_TIMESTEP = 0.002  # ps (2 fs)

# Analysis parameters
DEFAULT_TRAJECTORY_STRIDE = 1000
DEFAULT_ANALYSIS_REFERENCE_FRAME = 0

# Job queue
DEFAULT_MAX_WORKERS = 4
DEFAULT_GPU_ENABLED = False
DEFAULT_THREADS = 4
